[package]
name = "egui_overlay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glfw = { version = "0.44.0", git = "https://github.com/coderedart/glfw-rs.git", features = ["all"] }
bytemuck = "1"
egui = { version = "0.17.0", features = ["convert_bytemuck", "default_fonts"] }
wgpu = {version = "*", git = "https://github.com/gfx-rs/wgpu.git"}

[dev-dependencies]
pollster = "0.2"